version: '3'
services:
  redis:
    image: redis
    restart: always
    volumes:
      - redis:/data
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./superset/postresql/data:/var/lib/postgresql/data"
      - "./superset/postresql/init/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql"
  superset:
    image: amancevice/superset:latest
    restart: always
    depends_on:
      - redis
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
      SUPERSET_CONFIG_PATH: /etc/superset/superset-config.py
    ports:
      - "8088:8088"
    volumes:
      - ./superset/superset-config.py:/etc/superset/superset-config.py
  worker:
    image: amancevice/superset:latest
    restart: always
    depends_on:
      - redis
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
      SUPERSET_CONFIG_PATH: /etc/superset/superset-config.py
    volumes:
      - ./superset/superset-config.py:/etc/superset/superset-config.py
    command: "celery worker --app=superset.tasks.celery_app:app"
    healthcheck:
      test: ["CMD", "celery", "-A", "superset.tasks.celery_app:app", "status"]
volumes:
  redis: {}
